version: "3.8"

services:
  django:
    build: .
    container_name: api_currency
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
   pgdata:



